version: '2'
services:
  mysql:
    container_name: sapr-db
    restart: always
    image: postgres:9
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASS: 'postgres'
      POSTGRES_DB: 'sapr'
    volumes:
      - ./data/:/var/lib/postgresql/
    ports:
      - 5432:5432